from pathlib import Path
p=Path(__file__).parent/'dist'
nav=[('index.html','صفحۂ اول'),('education.html','تعلیمی شعبے'),('welfare.html','خدمتِ خلق'),('about.html','ہمارا تعارف'),('announcements.html','اعلانات'),('gallery.html','تصاویر'),('donate.html','عطیات'),('contact.html','رابطہ')]
def button(t,url,cls='primary'):return f'<a class="button {cls}" href="{url}">{t}<span aria-hidden="true">↗</span></a>'
def head(k,title):
 return f'''<!doctype html><html lang="ur" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | اقصیٰ اسلامک سنٹر، تونسہ شریف</title><meta name="description" content="اقصیٰ اسلامک سنٹر، جامع مسجد اقصیٰ اور اقصیٰ کمیونٹی سنٹر، ٹبہ امام تونسہ شریف۔ بچوں اور بچیوں کے لیے دینی و عصری تعلیم اور عوام الناس کی فلاح۔"><meta name="theme-color" content="#073f45"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/premium.css?v=20260914-2"><script defer src="assets/app.js"></script></head><body><a class="skip" href="#main">اصل مواد پر جائیں</a><div class="topbar"><div class="wrap"><span>علم، تربیت اور خدمتِ انسانیت</span><a href="tel:+923452656663" dir="ltr">0345 2656663</a><span>پتہ: ٹبہ امام، تونسہ شریف</span></div></div><header><div class="wrap header"><a href="index.html" class="brand"><span class="logo"><img src="assets/academy.jpg" alt="اقصیٰ اسلامک سنٹر کا لوگو"></span><span><strong>اقصیٰ اسلامک سنٹر</strong><small>AQSA ISLAMIC CENTRE</small></span></a><button class="menu" aria-label="مینو کھولیں" aria-expanded="false" aria-controls="navigation">☰</button><nav id="navigation">{''.join(f'<a href="{u}" '+('aria-current="page"' if u==k else '')+f'>{t}</a>' for u,t in nav)}</nav><a class="header-donate" href="donate.html">تعاون کیجیے ↗</a></div></header><main id="main">'''
def foot():return '''</main><footer><div class="wrap footer-grid"><div><h2>اقصیٰ اسلامک سنٹر</h2><p>قرآن سے وابستگی، علم سے روشنی،<br>اور خدمت سے معاشرے کی بہتری۔</p><small>AQSA ISLAMIC CENTRE · TAUNSA SHARIF</small></div><div><h3>ہمارے ادارے</h3><a href="education.html">اقصیٰ اسلامک سنٹر</a><a href="about.html#masjid">جامع مسجد اقصیٰ</a><a href="welfare.html">اقصیٰ کمیونٹی سنٹر</a></div><div><h3>رابطہ کیجیے</h3><p>پتہ: ٹبہ امام، تونسہ شریف</p><a href="tel:+9233336156660" dir="ltr">0333 6156660</a><a href="tel:+923452656663" dir="ltr">0345 2656663</a><a href="https://www.facebook.com/markazalrahmapk" target="_blank" rel="noopener">فیس بک پیج ↗</a></div></div><div class="wrap bottom">اقصیٰ اسلامک سنٹر · جامع مسجد اقصیٰ · اقصیٰ کمیونٹی سنٹر</div></footer><a class="whatsapp-float" href="https://wa.me/923452656663?text=السلام%20علیکم،%20اقصیٰ%20اسلامک%20سنٹر%20کے%20متعلق%20معلومات%20چاہییں۔" target="_blank" rel="noopener noreferrer" aria-label="واٹس ایپ پر رابطہ کریں" title="واٹس ایپ پر رابطہ کریں"><span class="whatsapp-symbol"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M20.52 3.48A11.86 11.86 0 0 0 12.04 0C5.46 0 .1 5.35.1 11.94c0 2.1.55 4.15 1.6 5.96L0 24l6.25-1.64a11.9 11.9 0 0 0 5.79 1.48h.01c6.58 0 11.94-5.35 11.95-11.94a11.87 11.87 0 0 0-3.48-8.42ZM12.05 21.8h-.01a9.87 9.87 0 0 1-5.03-1.38l-.36-.21-3.71.97.99-3.62-.24-.38a9.89 9.89 0 0 1-1.51-5.24c0-5.47 4.45-9.92 9.93-9.92 2.65 0 5.14 1.04 7.01 2.91a9.86 9.86 0 0 1 2.9 7.02c0 5.47-4.45 9.92-9.97 9.92Zm5.44-7.43c-.3-.15-1.77-.87-2.04-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.48-.89-.79-1.49-1.77-1.67-2.07-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.18.2-.3.3-.5.1-.2.05-.37-.03-.52-.07-.15-.67-1.62-.92-2.22-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.49s1.07 2.89 1.22 3.09c.15.2 2.1 3.2 5.09 4.49.71.3 1.26.48 1.69.62.71.23 1.36.2 1.87.12.57-.08 1.77-.72 2.02-1.42.25-.7.25-1.3.17-1.42-.07-.13-.27-.2-.57-.35Z"/></svg></span></a><div id="notice" role="status" aria-live="polite"></div></body></html>'''.replace('+9233336156660','+923336156660')
def intro(label,title,desc):return f'<section class="page-head"><div class="wrap"><a class="breadcrumb" href="index.html">صفحۂ اول /</a><span class="eyebrow">{label}</span><h1>{title}</h1><p>{desc}</p></div></section>'
courses=[('01','ناظرہ قرآن','قرآنِ کریم کی درست تلاوت کی بنیاد','بچوں اور بچیوں کے لیے ناظرہ قرآن کی تعلیم؛ قرآنِ کریم سے تعلق کی ابتدا۔'),('02','حفظ القرآن','حفظ کے ساتھ مڈل تک عصری تعلیم','قرآنِ کریم کے حفظ کے ساتھ مڈل تک تعلیم، تاکہ دینی اور عصری تعلیم کا سفر ساتھ جاری رہے۔'),('03','درسِ نظامی','درسِ نظامی اور عصری تعلیم','درسِ نظامی کے ساتھ عصری تعلیم کا مربوط اہتمام، تاکہ طلبہ دینی علوم کے ساتھ جدید تعلیمی تقاضوں سے بھی ہم آہنگ رہیں۔'),('04','عصری تعلیم','علم کے وسیع مواقع','دینی تعلیم کے ساتھ اسکول کی تعلیم کا تسلسل، بچوں اور بچیوں دونوں کے لیے۔')]
def course_photo(index,title):
 if index == 3:
  return f'<div class="scene scene-3 representative" role="img" aria-label="{title} کی نمائندہ تصویر"></div>'
 image_map={0:'quran-class.webp',1:'students-blue.webp',2:'students-group.webp'}
 return f'<div class="scene real-photo"><img src="assets/photos/{image_map[index]}" alt="{title}" loading="lazy"></div>'
def project_photo(index,title):
 return f'<div class="scene scene-{index+4} representative" role="img" aria-label="{title} کی نمائندہ تصویر"></div>'
def coursecards():
 return '<div class="grid four">'+''.join(f'<article class="card course">'+course_photo(int(n)-1,t)+f'<div class="course-content"><span class="course-index"><span class="num">{n}</span><span>تعلیمی شعبہ</span></span><h3>{t}</h3><strong>{s}</strong><p>{d}</p><a class="text-link" href="contact.html?subject={t}">معلومات حاصل کریں ←</a></div></article>' for n,t,s,d in courses)+'</div>'

projects=[('01','صاف پانی','واٹر پروجیکٹ','عوام الناس کے لیے پانی کی سہولت فراہم کرنے کے منصوبے۔'),('02','راشن کی فراہمی','ضرورت مند گھرانوں کا سہارا','ضرورت مند خاندانوں کے لیے راشن اور خوراک کی فراہمی۔'),('03','ادویات کی فراہمی','مریضوں کے لیے تعاون','ضرورت مند مریضوں کی ادویات کے سلسلے میں مدد۔'),('04','بیواؤں کی کفالت','زندگی کی ضروریات میں ساتھ','بیوہ خواتین کی ضروریات پوری کرنے کے لیے فلاحی تعاون۔'),('05','یتیم بچوں کی کفالت','تعلیم اور بہتر مستقبل','یتیم بچوں کی کفالت اور ان کی ضروریات میں مدد۔')]
def projectrows():
 return '<div class="project-list">'+''.join(f'<a href="donate.html" class="project">'+project_photo(int(n)-1,t)+f'<div class="project-content"><span class="project-category">{s}</span><h3>{t}</h3><p>{d}</p><span class="project-action">تعاون کی تفصیلات ←</span></div></a>' for n,t,s,d in projects)+'</div>'

def team():return '''<div class="team"><article class="patron"><span class="eyebrow">سرپرستی و رہنمائی</span><h3>ڈاکٹر حافظ عبد الکریم صاحب</h3><p>امیر مرکزی جمعیت اہلِ حدیث پاکستان</p></article><article><span>زیرِ سرپرستی</span><h3>امِ اقصیٰ احمد صاحبہ</h3></article><article><span>زیرِ نگرانی</span><h3>محترم جناب محمد اطہر صاحب</h3></article><article><span>مدیر</span><h3>قاری محمد رفیق تونسوی</h3></article></div>'''
home='''<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><div class="eyebrow">بچوں اور بچیوں کے لیے دینی و عصری تعلیم</div><span class="hero-kicker" dir="ltr">AQSA · EDUCATION & WELFARE</span><h1>علم کی روشنی۔<br><em>خدمت کی پہچان۔</em></h1><p>اقصیٰ اسلامک سنٹر بچوں اور بچیوں کو دینی تعلیم، عصری آگہی اور عملی تربیت کا مربوط ماحول فراہم کرتا ہے۔ جامع مسجد اقصیٰ روحانی رہنمائی کا مرکز ہے، جبکہ اقصیٰ کمیونٹی سنٹر عوامی خدمت کے منصوبوں کو منظم کرتا ہے۔</p><div class="actions">'''+button('ہمارے تعلیمی شعبے','education.html')+button('خدمت میں شریک ہوں','donate.html','outline')+'''</div><div class="hero-note"><span>۴ تعلیمی شعبے</span><i></i><span>دینی و عصری تعلیم ساتھ ساتھ</span></div></div><div class="hero-visual"><div class="photo-window scene real-photo"><img src="assets/photos/students-group.webp" alt="اقصیٰ اسلامک سنٹر کے طلبہ" fetchpriority="high"></div><div class="photo-caption"><span>اقصیٰ اسلامک سنٹر</span><strong>آج کی تعلیم، کل کی تعمیر</strong></div><div class="visual-label"><span>تعلیم، تربیت، خدمت</span><strong>ایک روشن مقصد</strong></div></div></div></section><div class="identity-strip"><div class="wrap"><a href="education.html"><span>تعلیم و تربیت</span><strong>اقصیٰ اسلامک سنٹر</strong></a><a href="about.html#masjid"><span>عبادت و تعلق باللہ</span><strong>جامع مسجد اقصیٰ</strong></a><a href="welfare.html"><span>رفاہ و فلاح</span><strong>اقصیٰ کمیونٹی سنٹر</strong></a></div></div><section class="section wrap"><div class="section-title"><div><span class="eyebrow">ہمارے تعلیمی شعبے</span><h2>دین کی بنیاد، دنیا کی تیاری</h2></div><p>بچوں اور بچیوں کے لیے چار منظم شعبے؛<br>قرآن، دینی علوم اور عصری تعلیم کا مربوط سفر۔</p></div>'''+coursecards()+'''</section><section class="welfare-section"><div class="wrap split"><div><span class="eyebrow">اقصیٰ کمیونٹی سنٹر</span><h2>خدمت کا ہاتھ،<br>امید کا ساتھ۔</h2><p>پانی، راشن، ادویات اور کفالت کے منصوبوں کے ذریعے عوام الناس کی ضروریات میں تعاون۔ آپ بھی اس خدمت کا حصہ بن سکتے ہیں۔</p>'''+button('فلاحی منصوبے دیکھیے','welfare.html')+'''</div>'''+projectrows()+'''</div></section><section class="section wrap"><div class="section-title"><div><span class="eyebrow">سرپرستی اور انتظام</span><h2>رہنمائی سے عمل تک</h2></div><a class="text-link" href="about.html">ادارے کا تعارف ←</a></div>'''+team()+'''</section><section class="wrap callout"><div><span class="eyebrow">آپ کا تعاون، کسی کا سہارا</span><h2>بھلائی کے اس سفر میں شریک ہوں</h2><p>تعلیم اور خدمتِ خلق کے منصوبوں کے لیے بینک یا موبائل اکاؤنٹ کے ذریعے تعاون کیجیے۔</p></div>'''+button('عطیات کی تفصیلات','donate.html')+'''</section>'''
education=intro('تعلیم و تربیت','قرآن کے ساتھ، تعلیم کے ساتھ','بچوں اور بچیوں دونوں کے لیے ناظرہ، حفظ القرآن، درسِ نظامی اور عصری تعلیم۔')+'<section class="section wrap">'+coursecards()+'''<div class="learning"><span class="eyebrow">تعلیمی تسلسل</span><h2>دینی تعلیم کے ساتھ اسکول کی تعلیم</h2><div class="grid two"><article><h3>حفظ القرآن + مڈل</h3><p>حفظ القرآن کے ساتھ مڈل تک عصری تعلیم دی جاتی ہے۔</p></article><article><h3>درسِ نظامی کے ساتھ عصری تعلیم</h3><p>درسِ نظامی کے ساتھ عصری تعلیم کا مربوط اہتمام؛ دینی فہم اور عصری علم کی متوازن بنیاد۔</p></article></div></div><div class="admission-panel"><div><span class="eyebrow">داخلہ و رہنمائی</span><h2>اپنے بچے کے تعلیمی سفر کا آغاز کیجیے</h2><p>عمر، جماعت، اوقات، فیس اور داخلے کے طریقۂ کار کی درست معلومات انتظامیہ سے حاصل کیجیے۔</p>'''+button('داخلے کے لیے رابطہ','contact.html?subject=داخلہ')+'''</div><figure class="admission-poster"><img src="assets/photos/admission-poster.webp" alt="اقصیٰ اسلامک سنٹر کا داخلہ اشتہار" loading="lazy"></figure></div></section>'''
welfare=intro('رفاہی و فلاحی منصوبے','خدمتِ خلق، ہماری مشترکہ ذمہ داری','اقصیٰ کمیونٹی سنٹر کے ذریعے عوام الناس کے لیے جاری خدمت کے منصوبے۔')+'<section class="section wrap split"><div>'+projectrows()+button('کسی منصوبے میں تعاون کریں','donate.html')+'</div><figure class="poster"><img src="assets/photos/welfare-poster.webp" alt="اقصیٰ اسلامک سنٹر کا فلاحی منصوبوں اور عطیات کا اصل اشتہار" loading="lazy"><figcaption>ادارے کی فلاحی سرگرمیاں اور تعاون کی تفصیلات</figcaption></figure></section>'
about=intro('ہمارا تعارف','ایک مرکز، تعلیم اور خدمت کے کئی راستے','اقصیٰ اسلامک سنٹر، جامع مسجد اقصیٰ اور اقصیٰ کمیونٹی سنٹر — ٹبہ امام، تونسہ شریف۔')+'''<section class="section wrap"><div class="grid three"><article class="card institution"><div class="scene real-photo"><img src="assets/photos/centre-exterior.webp" alt="اقصیٰ اسلامک سنٹر کی عمارت" loading="lazy"></div><span class="num">01</span><h2>اقصیٰ اسلامک سنٹر</h2><p>بچوں اور بچیوں کے لیے ناظرہ قرآن، حفظ القرآن، درسِ نظامی اور عصری تعلیم کا ادارہ۔</p></article><article class="card institution" id="masjid"><div class="scene real-photo"><img src="assets/photos/masjid-exterior.webp" alt="جامع مسجد اقصیٰ کی عمارت" loading="lazy"></div><span class="num">02</span><h2>جامع مسجد اقصیٰ</h2><p>مرکز سے وابستہ جامع مسجد؛ عبادت اور اللہ تعالیٰ سے تعلق کی مضبوطی کا مقام۔</p></article><article class="card institution"><div class="scene real-photo"><img src="assets/photos/community-group.webp" alt="اقصیٰ کمیونٹی سنٹر سے وابستہ افراد" loading="lazy"></div><span class="num">03</span><h2>اقصیٰ کمیونٹی سنٹر</h2><p>صاف پانی، راشن، ادویات، بیواؤں اور یتیم بچوں کی کفالت کے لیے رفاہی و فلاحی کام۔</p></article></div><div class="section-title spaced"><div><span class="eyebrow">ہماری انتظامیہ</span><h2>سرپرستی، نگرانی اور نظم</h2></div></div>'''+team()+'''<p class="source">ڈاکٹر حافظ عبد الکریم صاحب کے جماعتی عہدے کا <a href="https://www.nawaiwaqt.com.pk/26-May-2025/1898097" target="_blank" rel="noopener">حوالہ ↗</a></p></section>'''
accounts=[('Bank of Punjab','بینک آف پنجاب','PK54BPUN6110155995800020'),('Bank Alfalah','بینک الفلاح','PK40ALFH0075001007312234'),('easypaisa','ایزی پیسہ','03452566663'),('JazzCash','جاز کیش','03025257875')]
donate=intro('عطیات و تعاون','آپ کا تعاون، بھلائی کا تسلسل','تعلیم، پانی، راشن، ادویات اور کفالت کے منصوبوں میں حسبِ استطاعت حصہ لیجیے۔')+'<section class="section wrap"><div class="section-title"><div><span class="eyebrow">تعاون کے ذرائع</span><h2>بینک اور موبائل اکاؤنٹس</h2></div><a href="assets/photos/welfare-poster.webp" target="_blank" class="text-link">اصل گرافکس دیکھیے ↗</a></div><div class="grid two">'+''.join(f'<article class="account"><div class="bank-header"><span class="bank-name" dir="ltr">{en}</span><span class="bank-type">{('بینک ٹرانسفر' if v.startswith('PK') else 'موبائل والیٹ')}</span></div><h3>{ur}</h3><span class="account-label">'+('IBAN' if v.startswith('PK') else 'موبائل اکاؤنٹ نمبر')+f'</span><div class="account-number" dir="ltr">{' '.join(v[i:i+4] for i in range(0,len(v),4)) if v.startswith('PK') else v[:4]+' '+v[4:]}</div><button class="copy" data-copy="{v}">نمبر کاپی کریں <span aria-hidden="true">⧉</span></button></article>' for en,ur,v in accounts)+'''</div><div class="note"><h3>رقم بھیجنے سے پہلے</h3><p>یہ تفصیلات فراہم کردہ گرافکس سے لی گئی ہیں۔ اکاؤنٹ ٹائٹل گرافکس میں الگ درج نہیں؛ ادائیگی سے پہلے وصول کنندہ کا نام انتظامیہ سے ملا لیجیے۔</p></div><div class="donation-next"><h2>اپنا تعاون کسی منصوبے کے لیے مختص کریں</h2><p>منتخب منصوبے اور بھیجی گئی رقم کی تفصیل انتظامیہ کو واٹس ایپ پر بتا سکتے ہیں۔</p>'''+button('انتظامیہ سے واٹس ایپ پر رابطہ','https://wa.me/923452656663?text=السلام%20علیکم،%20مجھے%20عطیات%20کے%20متعلق%20معلومات%20چاہییں۔')+'</div></section>'
contact=intro('ہم سے رابطہ','تعلیم یا تعاون، بات یہیں سے شروع ہو','داخلے، تعلیمی شعبوں اور فلاحی منصوبوں کی معلومات کے لیے انتظامیہ سے رابطہ کریں۔')+'''<section class="section wrap split"><div><h2>اقصیٰ اسلامک سنٹر</h2><p class="address"><span>پتہ</span>ٹبہ امام، تونسہ شریف</p><div class="contact-line"><span>رابطہ نمبر</span><a dir="ltr" href="tel:+923336156660">0333 6156660</a></div><div class="contact-line"><span>رابطہ / واٹس ایپ</span><a dir="ltr" href="tel:+923452656663">0345 2656663</a></div><div class="actions">'''+button('فیس بک پیج','https://www.facebook.com/markazalrahmapk','outline')+button('نقشے پر تلاش کریں','https://www.google.com/maps/search/?api=1&query=ٹبہ+امام+تونسہ+شریف','outline')+'''</div><p>آمد سے پہلے فون پر اوقات اور مقام کی تصدیق کر لیجیے۔</p></div><form id="contact-form" class="contact-form"><span class="eyebrow">واٹس ایپ پر معلومات حاصل کریں</span><h2>آپ کس بارے میں جاننا چاہتے ہیں؟</h2><label for="name">آپ کا نام</label><input id="name" name="name" autocomplete="name" required placeholder="اپنا نام لکھیں"><label for="subject">موضوع</label><select id="subject" name="subject"><option>داخلہ</option><option>ناظرہ قرآن</option><option>حفظ القرآن</option><option>درسِ نظامی</option><option>عصری تعلیم</option><option>فلاحی منصوبے</option><option>عطیات</option><option>دیگر معلومات</option></select><label for="message">آپ کا پیغام</label><textarea id="message" name="message" rows="3" required placeholder="اپنا سوال لکھیے"></textarea><button class="button primary" type="submit">واٹس ایپ پر جاری رکھیں ↗</button><p class="form-help">پیغام واٹس ایپ میں کھلے گا؛ وہاں سے آپ اسے بھیج سکیں گے۔</p></form></section>'''
announcements=intro('اعلانات و تقریبات','ادارے کی سرگرمیاں اور اہم اعلانات','داخلوں، دینی اجتماعات اور سالانہ تقریبات سے متعلق تازہ معلومات ایک جگہ۔')+'''<section class="section wrap announcements-page"><article class="featured-event"><div class="featured-event-copy"><span class="event-badge">نمایاں اعلان</span><p class="event-overline">سالانہ اجتماع</p><h2>سالانہ قرآن و حدیث کانفرنس</h2><p>جامع مسجد اقصیٰ کے زیرِ اہتمام علم، اصلاح اور دینی رہنمائی کا بابرکت اجتماع۔ اکابر علمائے کرام کے خطابات اور قرآن و سنت کا پیغام عوام الناس تک پہنچانے کا اہتمام کیا جاتا ہے۔</p><div class="event-meta"><span>مقام: جامع مسجد اقصیٰ</span><span>ٹبہ امام، تونسہ شریف</span></div><p class="event-note">آئندہ کانفرنس کی تاریخ، مقررین اور مکمل پروگرام کا اعلان انتظامیہ کی جانب سے کیا جائے گا۔</p>'''+button('تازہ معلومات کے لیے رابطہ','contact.html?subject=سالانہ کانفرنس')+'''</div><figure class="featured-event-photo"><img src="assets/photos/conference-01.webp" alt="جامع مسجد اقصیٰ قرآن و حدیث کانفرنس" loading="eager"><figcaption>جامع مسجد اقصیٰ میں منعقدہ قرآن و حدیث کانفرنس</figcaption></figure></article><div class="section-title event-heading"><div><span class="eyebrow">تقریبات کی جھلکیاں</span><h2>علمی و دعوتی اجتماعات</h2></div><p>جامع مسجد اقصیٰ کے زیرِ اہتمام منعقد ہونے والی دینی تقریبات کی تصویری جھلکیاں۔</p></div><div class="event-gallery">'''+''.join(f'<figure><img src="assets/photos/conference-{i:02}.webp" alt="جامع مسجد اقصیٰ کانفرنس کی جھلک {i}" loading="lazy"><figcaption>سالانہ قرآن و حدیث کانفرنس</figcaption></figure>' for i in range(2,7))+'''</div><div class="announcement-cards"><article><span>01</span><h3>داخلہ و تعلیمی رہنمائی</h3><p>ناظرہ، حفظ القرآن، درسِ نظامی اور عصری تعلیم کے داخلوں اور اوقات کی معلومات انتظامیہ سے حاصل کیجیے۔</p><a class="text-link" href="contact.html?subject=داخلہ">معلومات حاصل کریں ←</a></article><article><span>02</span><h3>فلاحی منصوبوں میں تعاون</h3><p>صاف پانی، راشن، ادویات اور بیوہ و یتیم بچوں کی کفالت کے جاری منصوبوں میں شریک ہوں۔</p><a class="text-link" href="donate.html">تعاون کی تفصیلات ←</a></article></div></section>'''
exam_captions=['ششماہی امتحان کے دوران استاد طالب علم سے سبق سن رہے ہیں۔','ایک طالب علم اپنا سبق سنا رہا ہے۔','استاد طالب علم کی تیاری کا جائزہ لے رہے ہیں۔','زبانی امتحان کے دوران ایک طالب علم۔','استاد طلبہ سے سبق سن رہے ہیں۔','امتحان کے بعد طلبہ کی ایک یادگار تصویر۔','استاد کے سامنے سبق سناتے ہوئے طالب علم۔','امتحانی نشست میں سوالات کے جواب دیتا طالب علم۔','زبانی امتحان کی ایک سادہ سی جھلک۔','استاد طالب علم کا سبق سن رہے ہیں۔','جامعہ میں ششماہی تحریری امتحان کی جھلک۔','طلبہ خاموشی سے اپنے پرچے حل کر رہے ہیں۔','امتحان کے دوران اپنی نشستوں پر موجود طلبہ۔','سوالیہ پرچے حل کرتے ہوئے طلبہ۔','ششماہی امتحان میں مصروف طلبہ۔','جامعہ کے ہال میں جاری تحریری امتحان۔','قطار میں بیٹھے طلبہ امتحان دے رہے ہیں۔','نگرانی میں پرچہ حل کرتے ہوئے طلبہ۔','امتحانی ہال کا ایک منظر۔']
gallery=intro('تصویری گیلری','تعلیم، تربیت اور محنت کی روشن جھلکیاں','جامعہ کی علمی سرگرمیوں، امتحانات اور تربیتی ماحول کی منتخب تصاویر۔')+'''<section class="gallery-hero"><div class="wrap gallery-hero-grid"><div><span class="eyebrow">ششماہی امتحانات</span><h2>محنت کا جائزہ،<br>ترقی کی نئی منزل</h2><p>امتحان محض نتائج کا نام نہیں؛ یہ طلبہ کی علمی پیش رفت، اساتذہ کی محنت اور تربیتی نظم کا جامع جائزہ ہے۔</p><div class="gallery-stats"><span><strong>۱۹</strong> منتخب تصاویر</span><span><strong>۲</strong> امتحانی مراحل</span></div></div><figure><img src="assets/photos/exams/exam-11.webp" alt="جامعہ میں ششماہی امتحان کی جھلک"><figcaption>جامعہ میں ششماہی تحریری امتحان کی بامقصد اور منظم نشست</figcaption></figure></div></section><section class="section wrap"><div class="section-title"><div><span class="eyebrow">امتحانی سرگرمیاں</span><h2>طلبہ کی علمی پیش رفت کا جائزہ</h2></div><p>تحریری اور زبانی مراحل میں طلبہ کی تیاری، فہم اور تعلیمی تسلسل کو جانچا گیا۔</p></div><div class="exam-gallery">'''+''.join(f'<figure class="exam-photo {"portrait" if i in (13,17) else ""}"><a href="assets/photos/exams/exam-{i:02}.webp" target="_blank" aria-label="تصویر مکمل سائز میں دیکھیں"><img src="assets/photos/exams/exam-{i:02}.webp" alt="{caption}" loading="lazy"></a><figcaption><span>{i:02}</span><p>{caption}</p></figcaption></figure>' for i,caption in enumerate(exam_captions,1))+'''</div></section><section class="wrap gallery-callout"><div><span class="eyebrow">تعلیم کے ساتھ تربیت</span><h2>ہر طالب علم، ہماری ذمہ داری</h2><p>اقصیٰ اسلامک سنٹر میں دینی تعلیم، عصری آگہی اور کردار سازی کو ایک مربوط تعلیمی سفر بنایا گیا ہے۔</p></div>'''+button('تعلیمی شعبے دیکھیے','education.html')+'''</section>'''
for filename,title,body in [('index.html','صفحۂ اول',home),('education.html','تعلیمی شعبے',education),('welfare.html','خدمتِ خلق',welfare),('about.html','ہمارا تعارف',about),('announcements.html','اعلانات',announcements),('gallery.html','تصاویر',gallery),('donate.html','عطیات',donate),('contact.html','رابطہ',contact)]:
 (p/filename).write_text(head(filename,title)+body+foot())

# Keep the main photograph and management photograph tied to their exact subjects.
index_file=p/'index.html'
index_html=index_file.read_text().replace('assets/photos/students-group.webp" alt="اقصیٰ اسلامک سنٹر کے طلبہ','assets/photos/masjid-main-clean.webp" alt="جامع مسجد اقصیٰ، ٹبہ امام تونسہ شریف')
index_html=index_html.replace('<span>اقصیٰ اسلامک سنٹر</span><strong>آج کی تعلیم، کل کی تعمیر</strong>','<span>ٹبہ امام، تونسہ شریف</span><strong>جامع مسجد اقصیٰ</strong>')
announcement_preview='''<section class="section wrap announcement-preview"><div class="announcement-preview-card"><div><span class="eyebrow">اعلانات و تقریبات</span><h2>سالانہ قرآن و حدیث کانفرنس</h2><p>علم، اصلاح اور دینی رہنمائی کے بابرکت اجتماع کی تفصیلات اور گزشتہ تقریبات کی تصویری جھلکیاں دیکھیے۔</p>'''+button('اعلانات دیکھیے','announcements.html')+'''</div><figure><img src="assets/photos/conference-02.webp" alt="جامع مسجد اقصیٰ سالانہ قرآن و حدیث کانفرنس" loading="lazy"></figure></div></section>'''
index_html=index_html.replace('<section class="wrap callout">',announcement_preview+'<section class="wrap callout">')
index_file.write_text(index_html)
about_file=p/'about.html'
about_file.write_text(about_file.read_text().replace('<div class="section-title spaced">','<figure class="management-visual"><img src="assets/photos/management.webp" alt="اقصیٰ اسلامک سنٹر کے انتظامی و معزز اراکین" loading="lazy"><figcaption>ادارے کی انتظامی و تربیتی سرگرمیاں</figcaption></figure><div class="section-title spaced">'))
